package co.work.testpilot.extensions

import co.work.testpilot.runtime.ElementType
import platform.XCTest.*

private val xcUIElementTypeMap = mapOf(
    XCUIElementTypeAny to ElementType.Any,
    XCUIElementTypeOther to ElementType.Other,
    XCUIElementTypeApplication to ElementType.Application,
    XCUIElementTypeGroup to ElementType.Group,
    XCUIElementTypeWindow to ElementType.Window,
    XCUIElementTypeSheet to ElementType.Sheet,
    XCUIElementTypeDrawer to ElementType.Drawer,
    XCUIElementTypeAlert to ElementType.Alert,
    XCUIElementTypeDialog to ElementType.Dialog,
    XCUIElementTypeButton to ElementType.Button,
    XCUIElementTypeRadioButton to ElementType.RadioButton,
    XCUIElementTypeRadioGroup to ElementType.RadioGroup,
    XCUIElementTypeCheckBox to ElementType.CheckBox,
    XCUIElementTypeDisclosureTriangle to ElementType.DisclosureTriangle,
    XCUIElementTypePopUpButton to ElementType.PopUpButton,
    XCUIElementTypeComboBox to ElementType.ComboBox,
    XCUIElementTypeMenuButton to ElementType.MenuButton,
    XCUIElementTypeToolbarButton to ElementType.ToolbarButton,
    XCUIElementTypePopover to ElementType.Popover,
    XCUIElementTypeKeyboard to ElementType.Keyboard,
    XCUIElementTypeKey to ElementType.Key,
    XCUIElementTypeNavigationBar to ElementType.NavigationBar,
    XCUIElementTypeTabBar to ElementType.TabBar,
    XCUIElementTypeTabGroup to ElementType.TabGroup,
    XCUIElementTypeToolbar to ElementType.Toolbar,
    XCUIElementTypeStatusBar to ElementType.StatusBar,
    XCUIElementTypeTable to ElementType.Table,
    XCUIElementTypeTableRow to ElementType.TableRow,
    XCUIElementTypeTableColumn to ElementType.TableColumn,
    XCUIElementTypeOutlineRow to ElementType.OutlineRow,
    XCUIElementTypeBrowser to ElementType.Browser,
    XCUIElementTypeCollectionView to ElementType.CollectionView,
    XCUIElementTypeSlider to ElementType.Slider,
    XCUIElementTypePageIndicator to ElementType.PageIndicator,
    XCUIElementTypeProgressIndicator to ElementType.ProgressIndicator,
    XCUIElementTypeActivityIndicator to ElementType.ActivityIndicator,
    XCUIElementTypeSegmentedControl to ElementType.SegmentedControl,
    XCUIElementTypePicker to ElementType.Picker,
    XCUIElementTypePickerWheel to ElementType.PickerWheel,
    XCUIElementTypeSwitch to ElementType.Switch,
    XCUIElementTypeToggle to ElementType.Toggle,
    XCUIElementTypeLink to ElementType.Link,
    XCUIElementTypeImage to ElementType.Image,
    XCUIElementTypeIcon to ElementType.Icon,
    XCUIElementTypeSearchField to ElementType.SearchField,
    XCUIElementTypeScrollView to ElementType.ScrollView,
    XCUIElementTypeScrollBar to ElementType.ScrollBar,
    XCUIElementTypeStaticText to ElementType.StaticText,
    XCUIElementTypeTextField to ElementType.TextField,
    XCUIElementTypeSecureTextField to ElementType.SecureTextField,
    XCUIElementTypeDatePicker to ElementType.DatePicker,
    XCUIElementTypeTextView to ElementType.TextView,
    XCUIElementTypeMenu to ElementType.Menu,
    XCUIElementTypeMenuItem to ElementType.MenuItem,
    XCUIElementTypeMenuBar to ElementType.MenuBar,
    XCUIElementTypeMenuBarItem to ElementType.MenuBarItem,
    XCUIElementTypeMap to ElementType.Map,
    XCUIElementTypeWebView to ElementType.WebView,
    XCUIElementTypeIncrementArrow to ElementType.IncrementArrow,
    XCUIElementTypeDecrementArrow to ElementType.DecrementArrow,
    XCUIElementTypeTimeline to ElementType.Timeline,
    XCUIElementTypeRatingIndicator to ElementType.RatingIndicator,
    XCUIElementTypeValueIndicator to ElementType.ValueIndicator,
    XCUIElementTypeSplitGroup to ElementType.SplitGroup,
    XCUIElementTypeSplitter to ElementType.Splitter,
    XCUIElementTypeRelevanceIndicator to ElementType.RelevanceIndicator,
    XCUIElementTypeColorWell to ElementType.ColorWell,
    XCUIElementTypeHelpTag to ElementType.HelpTag,
    XCUIElementTypeMatte to ElementType.Matte,
    XCUIElementTypeDockItem to ElementType.DockItem,
    XCUIElementTypeRuler to ElementType.Ruler,
    XCUIElementTypeRulerMarker to ElementType.RulerMarker,
    XCUIElementTypeGrid to ElementType.Grid,
    XCUIElementTypeLevelIndicator to ElementType.LevelIndicator,
    XCUIElementTypeCell to ElementType.Cell,
    XCUIElementTypeLayoutArea to ElementType.LayoutArea,
    XCUIElementTypeLayoutItem to ElementType.LayoutItem,
    XCUIElementTypeHandle to ElementType.Handle,
    XCUIElementTypeStepper to ElementType.Stepper,
    XCUIElementTypeTab to ElementType.Tab,
    XCUIElementTypeTouchBar to ElementType.TouchBar,
    XCUIElementTypeStatusItem to ElementType.StatusItem,
)

fun XCUIElementType.toTestPilotElementType(): ElementType {
    return xcUIElementTypeMap[this] ?: ElementType.Unknown
}

fun ElementType.toXCUIElementType(): XCUIElementType {
    return xcUIElementTypeMap.entries.firstOrNull { it.value == this }?.key ?: XCUIElementTypeOther
}
