// swift-tools-version: 5.7

import PackageDescription

let package = Package(
    name: "TestPilotKit",
    platforms: [
        .macOS(.v13),
        .iOS(.v15),
    ],
    products: [
        .library(name: "TestPilotKit", targets: ["TestPilotKit"])
    ],
    dependencies: [],
    targets: [
        // The XCFramework generated by Kotlin
        .binaryTarget(
            name: "TestPilotShared",
            path: "../testpilot/build/XCFrameworks/debug/TestPilotShared.xcframework"
        ),
        // The Swift-friendly interface that consumes the Kotlin SDK
        .target(
            name: "TestPilotKit",
            dependencies: ["TestPilotShared"],
            path: "."
        )
    ]
)
